import { Inter } from "next/font/google";
import localeFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "./components/ThemeProvider";
import useTextDirection from "./libs/useTextDirection";
import NavBar from "./components/Nav/NavBar";
import NextAuthProvider from "../context/NextAuthProvider";
const inter = Inter({ subsets: ["latin"] });
const IranSansFont = localeFont({
  src: "../../assets/fonts/IRANSansX-Medium.ttf",
});
export const metadata = {
  title: "Questions Area",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params: { locale } }) {
  const direction = useTextDirection(locale);

  return (
    <html lang={locale} dir={direction} suppressHydrationWarning>
      <body
        // className={
        //   direction == "rtl" ? IranSansFont.className : inter.className
        // }
        className={IranSansFont.className}
      >
        <NextAuthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <NavBar />
            {children}
          </ThemeProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
